package tv.opentvcast.service

/**
 * Compile-time stub for [tv.opentvcast.service.CastService].
 *
 * The real service extends `android.app.Service` and depends on
 * NotificationCompat (AndroidX) and the R class (generated by AGP), none of
 * which exist in this standalone JVM runner.
 *
 * This stub supplies only the `companion object` members that ServiceController
 * references at compile time and that CastServiceTest asserts on. Every member
 * is a RE-EXPORT of [CastServiceContract] — the same single source of truth the
 * real service aliases — so this stub cannot drift from the real wire strings
 * by construction. (It used to hand-copy the literals and rely on
 * CastServiceTest to catch drift after the fact.)
 */
class CastService {
    companion object {
        val CHANNEL_ID      = CastServiceContract.CHANNEL_ID
        val NOTIFICATION_ID = CastServiceContract.NOTIFICATION_ID
        val ACTION_START    = CastServiceContract.ACTION_START
        val ACTION_STOP     = CastServiceContract.ACTION_STOP
        val ACTION_RESTART  = CastServiceContract.ACTION_RESTART
    }
}
